name: Full Auto Deploy MERN to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Debug folder structure
        run: |
          pwd
          ls
          ls frontend

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Install Docker & Run Containers on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "Starting deployment..."

            if ! command -v docker &> /dev/null
            then
              sudo apt update -y
              sudo apt install docker.io -y
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login \
              -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            sudo docker network create mern-network || true

            sudo docker stop mongo || true
            sudo docker rm mongo || true
            sudo docker run -d \
              --name mongo \
              --network mern-network \
              --restart always \
              -p 27017:27017 \
              -v mongo_data:/data/db \
              mongo

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker run -d \
              --name backend \
              --network mern-network \
              --restart always \
              -p 5000:5000 \
              -e MONGO_URL=mongodb://mongo:27017/mern_demo \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d \
              --name frontend \
              --restart always \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            echo "Deployment completed successfully"
